config/routes.rb
Rails.application.routes.draw do
  resources :messages

  resources :bid_offers

  resources :purchases

  resources :pila_packs do
    member do
      get 'buy'
    end
  end

  resources :tickets do
    member do
      get 'buy'
    end
    collection do
      get 'search'
    end
  end

  resources :offers do
    member do
      get 'buy'
    end
    member do
      get 'approve'
    end
    member do
      get 'finish_auction'
    end
    member do
      get 'approve'
    end
    collection do
      get 'search'
    end
  end

  root 'offers#show_all'
  get 'offers/show_all'

  devise_for :users
  resources :users, only: [:show, :index]

  get 'offer_report' => 'offers#report', as: 'offer_report'

end

app/models/bid_offer.rb
class BidOffer < ActiveRecord::Base
  belongs_to :offer
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/offer.rb
class Offer < ActiveRecord::Base
    belongs_to :users
    has_many :purchases
    has_many :bid_offers
    
    def self.search(name)
        search = "%" + name + "%"
        Offer.where("event_name LIKE ?", search) 
    end

end

app/models/pila_pack.rb
class PilaPack < ActiveRecord::Base
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  
  def self.search(name)
    search = "%" + name + "%"
    Ticket.where("event_name LIKE ?", search) 
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :tickets #TOOD excluir isso depois
  has_many :offers
  has_many :purchases
  has_many :bid_offers

  validates :balance, :numericality => { :greater_than_or_equal_to => 0 }
end

app/controllers/offer_controller.rb
class OfferController < ApplicationController
  def new
  end
  
  def search
    @offers = Offer.search params[:search]
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_filter :authenticate_user!, :except => [:show_all]
  before_action :set_offer, only: [:show, :edit, :update, :destroy, :buy, :approve]

  respond_to :html

  def index
    @offers = Offer.all
    respond_with(@offers)
  end

  def show_all
    @offers = Offer.limit(5).order('event_date asc')
    #@response = {:offers => @offers, :featuredOffers => @featuredOffers}
    respond_with(@offers)
  end

  def show
    respond_with(@offer)
  end

  def new
    @offer = Offer.new
    @offer.update_attribute(:isApproved, false)
    respond_with(@offer)
  end

  def edit
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.save
    respond_with(@offer)
  end

  def update
    @offer.update(offer_params)
    respond_with(@offer)
  end

  def destroy
    @offer.destroy
    respond_with(@offer)
  end

  def buy
    current_user.balance -= @offer.actual_price
    @offer.is_active = false
    @offerOwner = User.find(@offer.user_id)
    @offerOwner.balance += @offer.actual_price * 0.8
    begin
      ActiveRecord::Base.transaction do
        current_user.save!
        @offerOwner.save!
        @offer.save!
      end
    rescue
      redirect_to offers_path, alert: "Saldo insuficiente"
    end
  end

  def approve
    @offer = Offer.find(params[:id])
    @offer.update_attribute(:isApproved, true)
    redirect_to offers_path
  end

  def search
    @offers = Offer.search(params['name'])
    respond_with(@offers) do |format|
      format.html { render :action => :index }
    end

  end

  def finish_auction
    @offer = Offer.find(params[:id])
    @bid_offers = BidOffer.where(:offer_id => @offer.id)

    #@offer.update_attribute(:actual_price, @better_bid)
    @offer.update_attribute(:is_active, false)
    
    @offerOwner = User.find(@offer.user_id)
    @offerOwner.balance += @offer.actual_price * 0.8
    @offerOwner.save
    
    #@better_bid = 0
    #@winner = nil;

    #@bid_offers.each do |bid_offer|
    #  if bid_offer.value > @better_bid
    #    @better_bid = bid_offer.value
    #    @winner = bid_offer
    #  end
    #end

    #@user = User.find(@winner.user_id)

    #@user.balance -= @offer.actual_price
    #@user.save
  end

  def report
    report = UserReport.new
    render template: 'dossier/reports/show', locals: {report: report.run}
  end

  private
    def set_offer
      @offer = Offer.find(params[:id])
    end

    def offer_params
      params.require(:offer).permit(:user_id, :event_name, :event_date, :event_description, :is_active, :starting_price, :actual_price, :expire_date, :is_auction)
    end
end

app/controllers/pila_packs_controller.rb
class PilaPacksController < ApplicationController
  before_filter :authenticate_user! 
  before_action :set_pila_pack, only: [:show, :edit, :update, :destroy, :buy]

  respond_to :html

  def index
    @pila_packs = PilaPack.all
    respond_with(@pila_packs)
  end

  def show
    respond_with(@pila_pack)
  end

  def new
    @pila_pack = PilaPack.new
    respond_with(@pila_pack)
  end

  def edit
  end

  def create
    @pila_pack = PilaPack.new(pila_pack_params)
    @pila_pack.save
    respond_with(@pila_pack)
  end

  def update
    @pila_pack.update(pila_pack_params)
    respond_with(@pila_pack)
  end

  def destroy
    @pila_pack.destroy
    respond_with(@pila_pack)
  end
  
  def buy
    current_user.increment(:balance, @pila_pack.real_value)
    current_user.save
  end

  private
    def set_pila_pack
      @pila_pack = PilaPack.find(params[:id])
    end

    def pila_pack_params
      params.require(:pila_pack).permit(:name, :real_value, :pila_value)
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_filter :authenticate_user! 
  before_action :set_ticket, only: [:show, :edit, :update, :destroy, :buy]

  respond_to :html

  def index
    @tickets = Ticket.all
    respond_with(@tickets)
  end

  def show
    respond_with(@ticket)
  end

  def new
    @ticket = Ticket.new
    respond_with(@ticket)
  end

  def edit
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.save
    respond_with(@ticket)
  end

  def update
    @ticket.update(ticket_params)
    respond_with(@ticket)
  end

  def destroy
    @ticket.destroy
    respond_with(@ticket)
  end
  
  def buy
    @ticket.update_attribute(:active, false)
    current_user.decrement(:balance, @ticket.price)
    current_user.save
  end
  
  def search
    @tickets = Ticket.search(params['name'])
    respond_with(@tickets) do |format|
      format.html { render :action => :index }
    end
    
  end

  private
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    def ticket_params
      params.require(:ticket).permit(:user_id, :event_name, :event_date, :event_description, :active, :price)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  respond_to :html

  def index
    @users = User.all
    respond_with(@users)
  end

  def show
    @user = User.find(params[:id])
    @offers = Offer.where(:user_id => params[:id])
    @messages = Message.where(:userReceive => params[:id])

    respond_to do |format|
        format.html # show.html.erb
        format.xml { render :xml => @user }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def glypho(*names)
    content_tag :i, nil, class: names.map{|name| "icon-#{name.to_s.gsub('_','-')}" }
  end
end

app/helpers/bid_offers_helper.rb
module BidOffersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/offer_helper.rb
module OfferHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/pila_packs_helper.rb
module PilaPacksHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/pila_packs/_form.html.erb
<%= form_for(@pila_pack) do |f| %>
  <% if @pila_pack.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pila_pack.errors.count, "error") %> prohibited this pila_pack from being saved:</h2>

      <ul>
      <% @pila_pack.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :real_value %><br>
    <%= f.number_field :real_value %>
  </div>
  <div class="field">
    <%= f.label :pila_value %><br>
    <%= f.number_field :pila_value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pila_packs/buy.html.erb
<%- model_class = Ticket -%>
<div class="page-header">
  <h1>Compra de pila efetuada!</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Seu saldo</strong></dt>
  <dd><%= current_user.balance %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              tickets_path, :class => 'btn btn-default'  %>

app/views/pila_packs/edit.html.erb
<h1>Editing pila_pack</h1>

<%= render 'form' %>

<%= link_to 'Show', @pila_pack %> |
<%= link_to 'Back', pila_packs_path %>

app/views/pila_packs/index.html.erb
<h1>Listing pila_packs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Real value</th>
      <th>Pila value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pila_packs.each do |pila_pack| %>
      <tr>
        <td><%= pila_pack.name %></td>
        <td><%= pila_pack.real_value %></td>
        <td><%= pila_pack.pila_value %></td>
        <td><%= link_to 'Show', pila_pack %></td>
        <td>
          <%=
            if current_user.isModerator
              link_to 'Edit', edit_pila_pack_path(pila_pack)
            end
          %>
        </td>
        <td>
          <%=
            if current_user.isModerator
              link_to 'Destroy', pila_pack, method: :delete, data: { confirm: 'Are you sure?' }
            end
          %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%=
  if current_user.isModerator
    link_to 'New Pila pack', new_pila_pack_path
  end
%>

app/views/pila_packs/new.html.erb
<h1>New pila_pack</h1>

<%= render 'form' %>

<%= link_to 'Back', pila_packs_path %>

app/views/pila_packs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pila_pack.name %>
</p>

<p>
  <strong>Real value:</strong>
  <%= @pila_pack.real_value %>
</p>

<p>
  <strong>Pila value:</strong>
  <%= @pila_pack.pila_value %>
</p>

<%= link_to "Comprar", buy_pila_pack_path(@pila_pack), :class => 'btn btn-default' %>
<%= link_to 'Edit', edit_pila_pack_path(@pila_pack) %> |
<%= link_to 'Back', pila_packs_path %>