config/routes.rb
Rails.application.routes.draw do
  resources :messages

  resources :bid_offers

  resources :purchases

  resources :pila_packs do
    member do
      get 'buy'
    end
  end

  resources :tickets do
    member do
      get 'buy'
    end
    collection do
      get 'search'
    end
  end

  resources :offers do
    member do
      get 'buy'
    end
    member do
      get 'approve'
    end
    member do
      get 'finish_auction'
    end
    member do
      get 'approve'
    end
    collection do
      get 'search'
    end
  end

  root 'offers#show_all'
  get 'offers/show_all'

  devise_for :users
  resources :users, only: [:show, :index]

  get 'offer_report' => 'offers#report', as: 'offer_report'

end

app/models/bid_offer.rb
class BidOffer < ActiveRecord::Base
  belongs_to :offer
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/offer.rb
class Offer < ActiveRecord::Base
    belongs_to :users
    has_many :purchases
    has_many :bid_offers
    
    def self.search(name)
        search = "%" + name + "%"
        Offer.where("event_name LIKE ?", search) 
    end

end

app/models/pila_pack.rb
class PilaPack < ActiveRecord::Base
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  
  def self.search(name)
    search = "%" + name + "%"
    Ticket.where("event_name LIKE ?", search) 
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :tickets #TOOD excluir isso depois
  has_many :offers
  has_many :purchases
  has_many :bid_offers

  validates :balance, :numericality => { :greater_than_or_equal_to => 0 }
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @messages = Message.all
    respond_with(@messages)
  end

  def show
    respond_with(@message)
  end

  def new
    @message = Message.new
    @user = User.find(params[:user_id])
    respond_with(@message)
  end

  def edit
  end

  def create
    @message = Message.new(message_params)
    @message.save
    respond_with(@message)
  end

  def update
    @message.update(message_params)
    respond_with(@message)
  end

  def destroy
    @message.destroy
    respond_with(@message)
  end

  private
    def set_message
      @message = Message.find(params[:id])
    end

    def message_params
      params.require(:message).permit(:userSent, :userReceive, :message, :createdAt)
    end
end

app/controllers/offer_controller.rb
class OfferController < ApplicationController
  def new
  end
  
  def search
    @offers = Offer.search params[:search]
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_filter :authenticate_user!, :except => [:show_all]
  before_action :set_offer, only: [:show, :edit, :update, :destroy, :buy, :approve]

  respond_to :html

  def index
    @offers = Offer.all
    respond_with(@offers)
  end

  def show_all
    @offers = Offer.limit(5).order('event_date asc')
    #@response = {:offers => @offers, :featuredOffers => @featuredOffers}
    respond_with(@offers)
  end

  def show
    respond_with(@offer)
  end

  def new
    @offer = Offer.new
    @offer.update_attribute(:isApproved, false)
    respond_with(@offer)
  end

  def edit
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.save
    respond_with(@offer)
  end

  def update
    @offer.update(offer_params)
    respond_with(@offer)
  end

  def destroy
    @offer.destroy
    respond_with(@offer)
  end

  def buy
    current_user.balance -= @offer.actual_price
    @offer.is_active = false
    @offerOwner = User.find(@offer.user_id)
    @offerOwner.balance += @offer.actual_price * 0.8
    begin
      ActiveRecord::Base.transaction do
        current_user.save!
        @offerOwner.save!
        @offer.save!
      end
    rescue
      redirect_to offers_path, alert: "Saldo insuficiente"
    end
  end

  def approve
    @offer = Offer.find(params[:id])
    @offer.update_attribute(:isApproved, true)
    redirect_to offers_path
  end

  def search
    @offers = Offer.search(params['name'])
    respond_with(@offers) do |format|
      format.html { render :action => :index }
    end

  end

  def finish_auction
    @offer = Offer.find(params[:id])
    @bid_offers = BidOffer.where(:offer_id => @offer.id)

    #@offer.update_attribute(:actual_price, @better_bid)
    @offer.update_attribute(:is_active, false)
    
    @offerOwner = User.find(@offer.user_id)
    @offerOwner.balance += @offer.actual_price * 0.8
    @offerOwner.save
    
    #@better_bid = 0
    #@winner = nil;

    #@bid_offers.each do |bid_offer|
    #  if bid_offer.value > @better_bid
    #    @better_bid = bid_offer.value
    #    @winner = bid_offer
    #  end
    #end

    #@user = User.find(@winner.user_id)

    #@user.balance -= @offer.actual_price
    #@user.save
  end

  def report
    report = UserReport.new
    render template: 'dossier/reports/show', locals: {report: report.run}
  end

  private
    def set_offer
      @offer = Offer.find(params[:id])
    end

    def offer_params
      params.require(:offer).permit(:user_id, :event_name, :event_date, :event_description, :is_active, :starting_price, :actual_price, :expire_date, :is_auction)
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_filter :authenticate_user! 
  before_action :set_ticket, only: [:show, :edit, :update, :destroy, :buy]

  respond_to :html

  def index
    @tickets = Ticket.all
    respond_with(@tickets)
  end

  def show
    respond_with(@ticket)
  end

  def new
    @ticket = Ticket.new
    respond_with(@ticket)
  end

  def edit
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.save
    respond_with(@ticket)
  end

  def update
    @ticket.update(ticket_params)
    respond_with(@ticket)
  end

  def destroy
    @ticket.destroy
    respond_with(@ticket)
  end
  
  def buy
    @ticket.update_attribute(:active, false)
    current_user.decrement(:balance, @ticket.price)
    current_user.save
  end
  
  def search
    @tickets = Ticket.search(params['name'])
    respond_with(@tickets) do |format|
      format.html { render :action => :index }
    end
    
  end

  private
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    def ticket_params
      params.require(:ticket).permit(:user_id, :event_name, :event_date, :event_description, :active, :price)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  respond_to :html

  def index
    @users = User.all
    respond_with(@users)
  end

  def show
    @user = User.find(params[:id])
    @offers = Offer.where(:user_id => params[:id])
    @messages = Message.where(:userReceive => params[:id])

    respond_to do |format|
        format.html # show.html.erb
        format.xml { render :xml => @user }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def glypho(*names)
    content_tag :i, nil, class: names.map{|name| "icon-#{name.to_s.gsub('_','-')}" }
  end
end

app/helpers/bid_offers_helper.rb
module BidOffersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/offer_helper.rb
module OfferHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/pila_packs_helper.rb
module PilaPacksHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :userSent, value: current_user.id %>
  </div>
  <div class="field">
    <%= f.hidden_field :userReceive, value: @user.id %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="field">
    <%= f.label :createdAt %><br>
    <%= f.datetime_select :createdAt %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Listing messages</h1>

<table>
  <thead>
    <tr>
      <th>Usersent</th>
      <th>Userreceive</th>
      <th>Message</th>
      <th>Createdat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.userSent %></td>
        <td><%= message.userReceive %></td>
        <td><%= message.message %></td>
        <td><%= message.createdAt %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usersent:</strong>
  <%= @message.userSent %>
</p>

<p>
  <strong>Userreceive:</strong>
  <%= @message.userReceive %>
</p>

<p>
  <strong>Message:</strong>
  <%= @message.message %>
</p>

<p>
  <strong>Createdat:</strong>
  <%= @message.createdAt %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/tickets/_form.html.erb
<%= form_for @ticket, :html => { :class => "form-horizontal ticket" } do |f| %>

  <% if @ticket.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @ticket.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :user_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :user_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:user_id) %>
  </div>
  <div class="form-group">
    <%= f.label :event_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :event_name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:event_name) %>
  </div>
  <div class="form-group">
    <%= f.label :event_date, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :event_date, :class => 'form-control' %>
    </div>
    <%=f.error_span(:event_date) %>
  </div>
  <div class="form-group">
    <%= f.label :event_description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :event_description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:event_description) %>
  </div>
    <div class="form-group">
    <%= f.label :price, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :price, :class => 'form-control' %>
    </div>
    <%=f.error_span(:price) %>
  </div>
  <div class="form-group">
    <%= f.label :active, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.check_box :active, :class => 'form-control' %>
    </div>
    <%=f.error_span(:active) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tickets_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/tickets/buy.html.erb
<%- model_class = Ticket -%>
<div class="page-header">
  <h1>Compra efetuada!</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @ticket.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:event_name) %>:</strong></dt>
  <dd><%= @ticket.event_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:event_date) %>:</strong></dt>
  <dd><%= @ticket.event_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:event_description) %>:</strong></dt>
  <dd><%= @ticket.event_description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:active) %>:</strong></dt>
  <dd><%= @ticket.active %></dd>
  <dt><strong>Seu saldo</strong></dt>
  <dd><%= current_user.balance %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              tickets_path, :class => 'btn btn-default'  %>

app/views/tickets/edit.html.erb
<%- model_class = Ticket -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tickets/index.html.erb
<%- model_class = Ticket -%>
<div class="page-header">
	<div class="row">
		<div class="col-lg-9">
			<h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
		</div>		
		<div class="col-lg-3">
			<%= form_tag search_tickets_path, {:method => :get, :class => "form-search pull-right" } do %>									    	
	        	<input name="name" type="text" class="search-query">
	        	<button type="submit" class="btn">Buscar</button>		    
			<% end %>
		</div>
	</div>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:event_name) %></th>
      <th><%= model_class.human_attribute_name(:event_date) %></th>
      <th><%= model_class.human_attribute_name(:event_description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%= model_class.human_attribute_name(:active) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= link_to ticket.id, ticket_path(ticket) %></td>
        <td><%= ticket.user_id %></td>
        <td><%= ticket.event_name %></td>
        <td><%= ticket.event_date %></td>
        <td><%= ticket.event_description %></td>
        <td><%=l ticket.created_at %></td>
        <td><%= ticket.active %></td>
        <td><%= ticket.price %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_ticket_path(ticket), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      ticket_path(ticket),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_ticket_path,
            :class => 'btn btn-primary' %>

app/views/tickets/new.html.erb
<%- model_class = Ticket -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tickets/show.html.erb
<%- model_class = Ticket -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @ticket.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:event_name) %>:</strong></dt>
  <dd><%= @ticket.event_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:event_date) %>:</strong></dt>
  <dd><%= @ticket.event_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:event_description) %>:</strong></dt>
  <dd><%= @ticket.event_description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:active) %>:</strong></dt>
  <dd><%= @ticket.active %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @ticket.price %></dd>
</dl>

<%= link_to "Comprar", buy_ticket_path(@ticket), :class => 'btn btn-default' %>
<%= link_to t('.back', :default => t("helpers.links.back")),
              tickets_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_ticket_path(@ticket), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              ticket_path(@ticket),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>