config/routes.rb
Rails.application.routes.draw do
  resources :messages

  resources :bid_offers

  resources :purchases

  resources :pila_packs do
    member do
      get 'buy'
    end
  end

  resources :tickets do
    member do
      get 'buy'
    end
    collection do
      get 'search'
    end
  end

  resources :offers do
    member do
      get 'buy'
    end
    member do
      get 'approve'
    end
    member do
      get 'finish_auction'
    end
    member do
      get 'approve'
    end
    collection do
      get 'search'
    end
  end

  root 'offers#show_all'
  get 'offers/show_all'

  devise_for :users
  resources :users, only: [:show, :index]

  get 'offer_report' => 'offers#report', as: 'offer_report'

end

app/models/bid_offer.rb
class BidOffer < ActiveRecord::Base
  belongs_to :offer
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/offer.rb
class Offer < ActiveRecord::Base
    belongs_to :users
    has_many :purchases
    has_many :bid_offers
    
    def self.search(name)
        search = "%" + name + "%"
        Offer.where("event_name LIKE ?", search) 
    end

end

app/models/pila_pack.rb
class PilaPack < ActiveRecord::Base
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  
  def self.search(name)
    search = "%" + name + "%"
    Ticket.where("event_name LIKE ?", search) 
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :tickets #TOOD excluir isso depois
  has_many :offers
  has_many :purchases
  has_many :bid_offers

  validates :balance, :numericality => { :greater_than_or_equal_to => 0 }
end

app/controllers/offer_controller.rb
class OfferController < ApplicationController
  def new
  end
  
  def search
    @offers = Offer.search params[:search]
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_filter :authenticate_user!, :except => [:show_all]
  before_action :set_offer, only: [:show, :edit, :update, :destroy, :buy, :approve]

  respond_to :html

  def index
    @offers = Offer.all
    respond_with(@offers)
  end

  def show_all
    @offers = Offer.limit(5).order('event_date asc')
    #@response = {:offers => @offers, :featuredOffers => @featuredOffers}
    respond_with(@offers)
  end

  def show
    respond_with(@offer)
  end

  def new
    @offer = Offer.new
    @offer.update_attribute(:isApproved, false)
    respond_with(@offer)
  end

  def edit
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.save
    respond_with(@offer)
  end

  def update
    @offer.update(offer_params)
    respond_with(@offer)
  end

  def destroy
    @offer.destroy
    respond_with(@offer)
  end

  def buy
    current_user.balance -= @offer.actual_price
    @offer.is_active = false
    @offerOwner = User.find(@offer.user_id)
    @offerOwner.balance += @offer.actual_price * 0.8
    begin
      ActiveRecord::Base.transaction do
        current_user.save!
        @offerOwner.save!
        @offer.save!
      end
    rescue
      redirect_to offers_path, alert: "Saldo insuficiente"
    end
  end

  def approve
    @offer = Offer.find(params[:id])
    @offer.update_attribute(:isApproved, true)
    redirect_to offers_path
  end

  def search
    @offers = Offer.search(params['name'])
    respond_with(@offers) do |format|
      format.html { render :action => :index }
    end

  end

  def finish_auction
    @offer = Offer.find(params[:id])
    @bid_offers = BidOffer.where(:offer_id => @offer.id)

    #@offer.update_attribute(:actual_price, @better_bid)
    @offer.update_attribute(:is_active, false)
    
    @offerOwner = User.find(@offer.user_id)
    @offerOwner.balance += @offer.actual_price * 0.8
    @offerOwner.save
    
    #@better_bid = 0
    #@winner = nil;

    #@bid_offers.each do |bid_offer|
    #  if bid_offer.value > @better_bid
    #    @better_bid = bid_offer.value
    #    @winner = bid_offer
    #  end
    #end

    #@user = User.find(@winner.user_id)

    #@user.balance -= @offer.actual_price
    #@user.save
  end

  def report
    report = UserReport.new
    render template: 'dossier/reports/show', locals: {report: report.run}
  end

  private
    def set_offer
      @offer = Offer.find(params[:id])
    end

    def offer_params
      params.require(:offer).permit(:user_id, :event_name, :event_date, :event_description, :is_active, :starting_price, :actual_price, :expire_date, :is_auction)
    end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_purchase, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @purchases = Purchase.all
    respond_with(@purchases)
  end

  def show
    respond_with(@purchase)
  end

  def new
    @purchase = Purchase.new
    respond_with(@purchase)
  end

  def edit
  end

  def create
    @purchase = Purchase.new(purchase_params)
    @purchase.save
    respond_with(@purchase)
  end

  def update
    @purchase.update(purchase_params)
    respond_with(@purchase)
  end

  def destroy
    @purchase.destroy
    respond_with(@purchase)
  end

  private
    def set_purchase
      @purchase = Purchase.find(params[:id])
    end

    def purchase_params
      params.require(:purchase).permit(:user_id, :offer_id, :paid_value, :is_cancelled)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  respond_to :html

  def index
    @users = User.all
    respond_with(@users)
  end

  def show
    @user = User.find(params[:id])
    @offers = Offer.where(:user_id => params[:id])
    @messages = Message.where(:userReceive => params[:id])

    respond_to do |format|
        format.html # show.html.erb
        format.xml { render :xml => @user }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def glypho(*names)
    content_tag :i, nil, class: names.map{|name| "icon-#{name.to_s.gsub('_','-')}" }
  end
end

app/helpers/bid_offers_helper.rb
module BidOffersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/offer_helper.rb
module OfferHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/pila_packs_helper.rb
module PilaPacksHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/purchases/_form.html.erb
<%= form_for(@purchase) do |f| %>
  <% if @purchase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
      <% @purchase.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :offer_id %><br>
    <%= f.number_field :offer_id %>
  </div>
  <div class="field">
    <%= f.label :paid_value %><br>
    <%= f.text_field :paid_value %>
  </div>
  <div class="field">
    <%= f.label :is_cancelled %><br>
    <%= f.check_box :is_cancelled %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/purchases/edit.html.erb
<h1>Editing purchase</h1>

<%= render 'form' %>

<%= link_to 'Show', @purchase %> |
<%= link_to 'Back', purchases_path %>

app/views/purchases/index.html.erb
<h1>Listing purchases</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Offer</th>
      <th>Paid value</th>
      <th>Is cancelled</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @purchases.each do |purchase| %>
      <tr>
        <td><%= purchase.user_id %></td>
        <td><%= purchase.offer_id %></td>
        <td><%= purchase.paid_value %></td>
        <td><%= purchase.is_cancelled %></td>
        <td><%= link_to 'Show', purchase %></td>
        <td><%= link_to 'Edit', edit_purchase_path(purchase) %></td>
        <td><%= link_to 'Destroy', purchase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Purchase', new_purchase_path %>

app/views/purchases/new.html.erb
<h1>New purchase</h1>

<%= render 'form' %>

<%= link_to 'Back', purchases_path %>

app/views/purchases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @purchase.user_id %>
</p>

<p>
  <strong>Offer:</strong>
  <%= @purchase.offer_id %>
</p>

<p>
  <strong>Paid value:</strong>
  <%= @purchase.paid_value %>
</p>

<p>
  <strong>Is cancelled:</strong>
  <%= @purchase.is_cancelled %>
</p>

<%= link_to 'Edit', edit_purchase_path(@purchase) %> |
<%= link_to 'Back', purchases_path %>