config/routes.rb
Rails.application.routes.draw do
  resources :messages

  resources :bid_offers

  resources :purchases

  resources :pila_packs do
    member do
      get 'buy'
    end
  end

  resources :tickets do
    member do
      get 'buy'
    end
    collection do
      get 'search'
    end
  end

  resources :offers do
    member do
      get 'buy'
    end
    member do
      get 'approve'
    end
    member do
      get 'finish_auction'
    end
    member do
      get 'approve'
    end
    collection do
      get 'search'
    end
  end

  root 'offers#show_all'
  get 'offers/show_all'

  devise_for :users
  resources :users, only: [:show, :index]

  get 'offer_report' => 'offers#report', as: 'offer_report'

end

app/models/offer.rb
class Offer < ActiveRecord::Base
    belongs_to :users
    has_many :purchases
    has_many :bid_offers
    
    def self.search(name)
        search = "%" + name + "%"
        Offer.where("event_name LIKE ?", search) 
    end

end

app/controllers/offer_controller.rb
class OfferController < ApplicationController
  def new
  end
  
  def search
    @offers = Offer.search params[:search]
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_filter :authenticate_user!, :except => [:show_all]
  before_action :set_offer, only: [:show, :edit, :update, :destroy, :buy, :approve]

  respond_to :html

  def index
    @offers = Offer.all
    respond_with(@offers)
  end

  def show_all
    @offers = Offer.limit(5).order('event_date asc')
    #@response = {:offers => @offers, :featuredOffers => @featuredOffers}
    respond_with(@offers)
  end

  def show
    respond_with(@offer)
  end

  def new
    @offer = Offer.new
    @offer.update_attribute(:isApproved, false)
    respond_with(@offer)
  end

  def edit
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.save
    respond_with(@offer)
  end

  def update
    @offer.update(offer_params)
    respond_with(@offer)
  end

  def destroy
    @offer.destroy
    respond_with(@offer)
  end

  def buy
    current_user.balance -= @offer.actual_price
    @offer.is_active = false
    @offerOwner = User.find(@offer.user_id)
    @offerOwner.balance += @offer.actual_price * 0.8
    begin
      ActiveRecord::Base.transaction do
        current_user.save!
        @offerOwner.save!
        @offer.save!
      end
    rescue
      redirect_to offers_path, alert: "Saldo insuficiente"
    end
  end

  def approve
    @offer = Offer.find(params[:id])
    @offer.update_attribute(:isApproved, true)
    redirect_to offers_path
  end

  def search
    @offers = Offer.search(params['name'])
    respond_with(@offers) do |format|
      format.html { render :action => :index }
    end

  end

  def finish_auction
    @offer = Offer.find(params[:id])
    @bid_offers = BidOffer.where(:offer_id => @offer.id)

    #@offer.update_attribute(:actual_price, @better_bid)
    @offer.update_attribute(:is_active, false)
    
    @offerOwner = User.find(@offer.user_id)
    @offerOwner.balance += @offer.actual_price * 0.8
    @offerOwner.save
    
    #@better_bid = 0
    #@winner = nil;

    #@bid_offers.each do |bid_offer|
    #  if bid_offer.value > @better_bid
    #    @better_bid = bid_offer.value
    #    @winner = bid_offer
    #  end
    #end

    #@user = User.find(@winner.user_id)

    #@user.balance -= @offer.actual_price
    #@user.save
  end

  def report
    report = UserReport.new
    render template: 'dossier/reports/show', locals: {report: report.run}
  end

  private
    def set_offer
      @offer = Offer.find(params[:id])
    end

    def offer_params
      params.require(:offer).permit(:user_id, :event_name, :event_date, :event_description, :is_active, :starting_price, :actual_price, :expire_date, :is_auction)
    end
end

app/helpers/offer_helper.rb
module OfferHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
<%= form_for(@offer) do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% @offer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= current_user.username %>
  </div>
  <div class="field">
    <%= f.label :event_name %><br>
    <%= f.text_field :event_name %>
  </div>
  <div class="field">
    <%= f.label :event_date %><br>
    <%= f.date_select :event_date %>
  </div>
  <div class="field">
    <%= f.label :event_description %><br>
    <%= f.text_area :event_description %>
  </div>
  <div class="field">
    <%= f.label :is_active %><br>
    <%= f.check_box :is_active %>
  </div>
  <div class="field">
    <%= f.label :starting_price %><br>
    <%= f.text_field :starting_price %>
  </div>
  <div class="field">
    <%= f.label :actual_price %><br>
    <%= f.text_field :actual_price %>
  </div>
  <div class="field">
    <%= f.label :expire_date %><br>
    <%= f.datetime_select :expire_date %>
  </div>
  <div class="field">
    <%= f.label :is_auction %><br>
    <%= f.check_box :is_auction %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offers/buy.html.erb
<%- model_class = Offer -%>
<div class="page-header">
  <h1>Compra efetuada!</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @offer.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:event_name) %>:</strong></dt>
  <dd><%= @offer.event_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:event_date) %>:</strong></dt>
  <dd><%= @offer.event_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:event_description) %>:</strong></dt>
  <dd><%= @offer.event_description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:is_active) %>:</strong></dt>
  <dd><%= @offer.is_active %></dd>
  <% if !@offer.is_auction %>
    <dt><strong>Seu saldo</strong></dt>
    <dd><%= current_user.balance %></dd>
  <% end %>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              offers_path, :class => 'btn btn-default'  %>

app/views/offers/edit.html.erb
<h1>Editing offer</h1>

<%= render 'form' %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

app/views/offers/finish_auction.html.erb
<%- model_class = Offer -%>
<div class="page-header">
  <h1>Compra efetuada!</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @offer.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:event_name) %>:</strong></dt>
  <dd><%= @offer.event_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:event_date) %>:</strong></dt>
  <dd><%= @offer.event_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:event_description) %>:</strong></dt>
  <dd><%= @offer.event_description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:is_active) %>:</strong></dt>
  <dd><%= @offer.is_active %></dd>
  <dt><strong>Seu saldo</strong></dt>
  <dd><%= current_user.balance %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              offers_path, :class => 'btn btn-default'  %>

app/views/offers/index.html.erb
<%- model_class = Offer -%>

<h1>Listing offers</h1>

<div class="col-lg-3">
		<%= form_tag search_offers_path, {:method => :get, :class => "form-search pull-right" } do %>
        	<input name="name" type="text" class="search-query">
        	<button type="submit" class="btn">Buscar</button>
		<% end %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:event_name) %></th>
      <th><%= model_class.human_attribute_name(:event_date) %></th>
      <th><%= model_class.human_attribute_name(:event_description) %></th>
      <th><%= model_class.human_attribute_name(:is_active) %></th>
      <th><%= model_class.human_attribute_name(:starting_price) %></th>
      <th><%= model_class.human_attribute_name(:actual_price) %></th>
      <th><%= model_class.human_attribute_name(:expire_date) %></th>
      <th><%= model_class.human_attribute_name(:is_auction) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offers.each do |offer| %>
			<% if offer.is_active %>
	      <tr>
	        <td><%= offer.user_id %></td>
	        <td><%= offer.event_name %></td>
	        <td><%= l offer.event_date, :format => "%d/%m/%Y"  %></td>
	        <td><%= offer.event_description %></td>
	        <td><%= offer.is_active?? "Ativo" : "Inativo" %></td>
	        <td><%= offer.starting_price %></td>
	        <td><%= offer.actual_price %></td>
	        <td><%= l offer.expire_date, :format => "%d/%m/%Y" %></td>
	        <td><%= offer.is_auction?? "Sim" : "Não" %></td>
					<td>
						<%=
						 	if current_user.isModerator
								link_to 'Aprovar', approve_offer_path(offer.id)
							end
						%>
					</td>
            <% if (offer.is_auction) %>
                <td><%= link_to "Dar lance", new_bid_offer_path(:offer => offer), :class => 'btn btn-default' %></td>
            <% else %>
	            <td><%= link_to "Comprar", buy_offer_path(offer), :class => 'btn btn-default' %></td>
            <% end %>
	        <td><%= link_to 'Mostrar', offer %></td>
	        <td>
						<% if current_user.isModerator %>
							<%= link_to 'Editar', edit_offer_path(offer) %>
						<% end %>
					</td>
	        <td>
						<% if current_user.isModerator %>
							<%= link_to 'Excluir', offer, method: :delete, data: { confirm: 'Are you sure?' } %>
						<% end %>
					</td>
	      </tr>
			<% end %>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Nova oferta', new_offer_path %>

app/views/offers/new.html.erb
<h1>New offer</h1>

<%= render 'form' %>

app/views/offers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @offer.user_id %>
</p>

<p>
  <strong>Event name:</strong>
  <%= @offer.event_name %>
</p>

<p>
  <strong>Event date:</strong>
  <%= @offer.event_date %>
</p>

<p>
  <strong>Event description:</strong>
  <%= @offer.event_description %>
</p>

<p>
  <strong>Is active:</strong>
  <%= @offer.is_active %>
</p>

<p>
  <strong>Starting price:</strong>
  <%= @offer.starting_price %>
</p>

<p>
  <strong>Actual price:</strong>
  <%= @offer.actual_price %>
</p>

<p>
  <strong>Expire date:</strong>
  <%= @offer.expire_date %>
</p>

<p>
  <strong>Is auction:</strong>
  <%= @offer.is_auction %>
</p>

<p>
  <strong>Is approved:</strong>
  <%= @offer.isApproved %>
</p>

<%= link_to 'Edit', edit_offer_path(@offer) %> |
<%= link_to 'Back', offers_path %>
<% if @offer.is_auction %>
    <%= link_to 'Finalizar leilão', finish_auction_offer_path %>
<% end %>

app/views/offers/show_all.html.erb
<%- model_class = Offer -%>

    <h2>Próximos Eventos</h2>


    <% @offers.each do |offer| %>
        <% if offer.is_active %>
            <div class="event">
              <img src="/assets/no-image.jpg">
              <span><%= offer.event_name %></span>
              <span><%= offer.event_date.to_time.strftime('%d/%m - %l:%M') %></span>
              <%= link_to(buy_offer_path(offer)) do %>
                  <div class="buyTicketButton">Comprar</div>
              <% end %>
            </div>
        <% end %>
    <% end %>